# Generated by Django 4.1.2 on 2022-11-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('audio', models.FileField(upload_to='audio/%Y/%m/%d/')),
                ('is_played', models.BooleanField(default=False)),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
