# Generated by Django 4.1.2 on 2022-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist_cover_playlist_description_playlist_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='head',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='music.composition'),
        ),
        migrations.DeleteModel(
            name='LinkedListItem',
        ),
    ]
