# Generated by Django 4.1.2 on 2022-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_playlist_tracks_playlist_compositions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='length',
        ),
        migrations.AddField(
            model_name='composition',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='compositions',
            field=models.ManyToManyField(to='music.composition'),
        ),
    ]
