# Generated by Django 4.1.2 on 2022-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_playlistscompositions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='compositions',
        ),
        migrations.AddField(
            model_name='playlist',
            name='compositions',
            field=models.ManyToManyField(through='music.PlaylistsCompositions',
                                         to='music.composition'),
        )
    ]
